-- This File Was Generated by GUI to Lua Plugin: K1
-- Plugin by Kepler
local gui = Instance.new("ScreenGui")
gui.Name = "K1"
gui.ResetOnSpawn = true
gui.IgnoreGuiInset = false
gui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")

local obj1 = Instance.new("Frame")
obj1.Name = "K2"
obj1.Size = UDim2.new(0, 300, 0, 100)
obj1.Position = UDim2.new(0.5, 0, 0.4, 0)
obj1.AnchorPoint = Vector2.new(0.5, 0.5)
obj1.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
obj1.BackgroundTransparency = 0
obj1.BorderSizePixel = 1
obj1.BorderColor3 = Color3.fromRGB(27, 42, 53)
obj1.Visible = true
obj1.ZIndex = 1
obj1.ClipsDescendants = false
obj1.Parent = gui

local obj2 = Instance.new("ImageLabel")
obj2.Name = "ImageLabel"
obj2.Size = UDim2.new(0, 50, 0, 50)
obj2.Position = UDim2.new(0.899, 0, 0.5, 0)
obj2.AnchorPoint = Vector2.new(0.5, 0.5)
obj2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
obj2.BackgroundTransparency = 1
obj2.BorderSizePixel = 0
obj2.BorderColor3 = Color3.fromRGB(27, 42, 53)
obj2.Visible = true
obj2.ZIndex = 1
obj2.Image = "rbxthumb://type=Asset&id=2577854643&w=420&h=420"
obj2.ImageColor3 = Color3.fromRGB(255, 255, 255)
obj2.ImageTransparency = 0
obj2.ScaleType = Enum.ScaleType.Stretch
obj2.Parent = obj1

local obj3 = Instance.new("UICorner")
obj3.Name = "UICorner"
obj3.Parent = obj2

local obj4 = Instance.new("TextButton")
obj4.Name = "TextButton"
obj4.Size = UDim2.new(0, 200, 0, 50)
obj4.Position = UDim2.new(0.1, 0, 0.6, 0)
obj4.AnchorPoint = Vector2.new(0, 0.5)
obj4.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
obj4.BackgroundTransparency = 0
obj4.BorderSizePixel = 2
obj4.BorderColor3 = Color3.fromRGB(255, 0, 0)
obj4.Visible = true
obj4.ZIndex = 1
obj4.Text = "Button"
obj4.TextSize = 8
obj4.TextColor3 = Color3.fromRGB(255, 255, 255)
obj4.TextTransparency = 0
obj4.TextWrapped = false
obj4.TextScaled = false
obj4.Font = Enum.Font.Legacy
obj4.TextXAlignment = Enum.TextXAlignment.Center
obj4.TextYAlignment = Enum.TextYAlignment.Center
obj4.Parent = obj1

local obj5 = Instance.new("UICorner")
obj5.Name = "UICorner"
obj5.Parent = obj4

local obj6 = Instance.new("TextLabel")
obj6.Name = "TextLabel"
obj6.Size = UDim2.new(0, 200, 0, 50)
obj6.Position = UDim2.new(0.2, 0, 0.1, 0)
obj6.AnchorPoint = Vector2.new(0.5, 0.5)
obj6.BackgroundColor3 = Color3.fromRGB(162, 162, 162)
obj6.BackgroundTransparency = 1
obj6.BorderSizePixel = 1
obj6.BorderColor3 = Color3.fromRGB(27, 42, 53)
obj6.Visible = true
obj6.ZIndex = 1
obj6.Text = "Kepler"
obj6.TextSize = 36
obj6.TextColor3 = Color3.fromRGB(27, 42, 53)
obj6.TextTransparency = 0
obj6.TextWrapped = false
obj6.TextScaled = false
obj6.Font = Enum.Font.Arcade
obj6.TextXAlignment = Enum.TextXAlignment.Center
obj6.TextYAlignment = Enum.TextYAlignment.Center
obj6.Parent = obj1

local obj7 = Instance.new("UICorner")
obj7.Name = "UICorner"
obj7.Parent = obj6

local obj8 = Instance.new("UICorner")
obj8.Name = "UICorner"
obj8.Parent = obj1

-- Drag Scripts

-- Drag Script for obj1
local UIS = game:GetService("UserInputService")
local dragging_obj1 = false
local dragStart_obj1 = nil
local startPos_obj1 = nil

obj1.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 or
       input.UserInputType == Enum.UserInputType.Touch then
        dragging_obj1 = true
        dragStart_obj1 = input.Position
        startPos_obj1 = obj1.Position
    end
end)

obj1.InputChanged:Connect(function(input)
    if dragging_obj1 and
       (input.UserInputType == Enum.UserInputType.MouseMovement or
        input.UserInputType == Enum.UserInputType.Touch) then
        local delta = input.Position - dragStart_obj1
        obj1.Position = UDim2.new(
            startPos_obj1.X.Scale,
            startPos_obj1.X.Offset + delta.X,
            startPos_obj1.Y.Scale,
            startPos_obj1.Y.Offset + delta.Y
        )
    end
end)

obj1.InputEnded:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 or
       input.UserInputType == Enum.UserInputType.Touch then
        dragging_obj1 = false
    end
end)

local fuck = false

obj4.MouseButton1Click:Connect(function()
   fuck = not fuck

if fuck then
while fuck do
print("Fuck?")
task.wait(0.1)
end
end
end)
